name: flutter_hopper
description: AudioHopperProject

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  badges: ^2.0.1
  basic_utils: ^3.6.1
  cached_network_image: ^3.1.0
  dartx: ^0.7.1
  rxdart: ^0.27.2
  stacked: ^1.7.6
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  flutter_icons: ^1.0.0+1
  google_fonts: ^2.1.0
  lottie: ^1.2.1
  flash: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  #flutter_launcher_name: any
  flutter_staggered_animations: ^1.0.0
  flutter_local_notifications: ^9.0.0
  firebase_messaging: ^10.0.8
  file_picker: ^4.1.3
  sleek_circular_slider: ^1.2.0
  otp_text_field: ^1.0.2
  just_audio: ^0.9.13
  audio_video_progress_bar: ^0.9.0
  audio_service: ^0.18.1
  url_launcher: ^6.0.12
  share_plus: ^3.0.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.1.2
  sign_in_with_apple: ^3.2.0
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  permission_handler: ^8.2.2
  flutter_downloader: 1.5.2
  android_path_provider: ^0.3.0
  path_provider: ^2.0.5
  firebase_dynamic_links: ^2.0.10
  intl: ^0.17.0
  device_info: ^2.0.2
  open_file: ^3.2.1
  in_app_purchase: ^1.0.9
  connectivity: ^3.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
#flutter_launcher_name:
 # name: "Audio Hopper"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
